# Use an official Eclipse Temurin base image
FROM eclipse-temurin:17
# Maintainer or author
LABEL maintainer="vijayaraghavan.1369@gmail.com"
# Set the working directory inside the container
WORKDIR /app
# Copy the application's JAR file into the container
COPY /target/docker-0.0.1-SNAPSHOT.jar /app/docker-0.0.1-SNAPSHOT.jar
# Define the ENTRYPOINT for the container. This command will be executed when the container starts
# Arguments provided to 'docker run' will be appended to this ENTRYPOINT
ENTRYPOINT ["java", "-jar", "/app/docker-0.0.1-SNAPSHOT.jar"]